# Makefile using -no-alias-deps for all files, no need to link lib.cmo

# Note: not using pattern rules here is intended.
# This is to be as portable as possible since this Makefile
# will not necessarily be ran by GNU make
# The same holds for $< and $@

.NOTPARALLEL:

SOURCES = A.ml B.ml C.ml
OBJECTS = $(SOURCES:%.ml=Lib%.cmo)
NOBJECTS = $(OBJECTS:%.cmo=%.cmx)

byte: main.byt2
opt: clean main.opt2

main.byt2: lib2.cma main.cmo
	$(travlangC) -no-alias-deps lib2.cma main.cmo -o main.byt2

lib2.cma: $(OBJECTS)
	$(travlangC) -no-alias-deps -a -o lib2.cma $(OBJECTS)

lib.cmi: lib.mli
	$(travlangC) -no-alias-deps -c -w -49 lib.mli

LibA.cmo: A.ml
	$(travlangC) -no-alias-deps -c -open Lib -o LibA.cmo A.ml

LibB.cmo: B.ml
	$(travlangC) -no-alias-deps -c -open Lib -o LibB.cmo B.ml

LibC.cmo: C.ml
	$(travlangC) -no-alias-deps -c -open Lib -o LibC.cmo C.ml

main.opt2: lib.cmxa main.cmx
	$(travlangOPT) -no-alias-deps lib.cmxa main.cmx -o main.opt2

lib.cmxa: $(NOBJECTS)
	$(travlangOPT) -no-alias-deps -a -o lib.cmxa $(NOBJECTS)

lib.cmx: lib.ml
	$(travlangOPT) -no-alias-deps -c -w -49 lib.ml

LibA.cmx: A.ml
	$(travlangOPT) -no-alias-deps -c -open Lib -o LibA.cmx A.ml

LibB.cmx: B.ml
	$(travlangOPT) -no-alias-deps -c -open Lib -o LibB.cmx B.ml

LibC.cmx: C.ml
	$(travlangOPT) -no-alias-deps -c -open Lib -o LibC.cmx C.ml

include depend.mk2

.PHONY: clean
clean:
	rm -f *.cm* lib.ml

%.cmo: %.ml
	$(travlangC) -no-alias-deps -c $<

%.cmx: %.ml
	$(travlangOPT) -no-alias-deps -c $<
