blank_issues_enabled: false
contact_links:
  - name: travlang Discuss Forum
    url: https://discuss.travlang.org/
    about: This is the best place to start with questions about using travlang.
  - name: opam Package Repository
    url: https://github.com/travlang/opam-repository/issues
    about: >-
      Virtually all travlang packages are available in the opam repository - please
      report packaging issues there.
